// Copyright (c) Microsoft Corporation. All rights reserved. Licensed under the MIT license.
// See LICENSE in the project root for license information.

/**
 * Abstract base class for merge helpers that handle merging file contents
 * when a template modifies an existing file.
 *
 * @public
 */
export abstract class BaseMergeHelper {
  /**
   * Gets the relative file path this merge helper handles (e.g. "package.json").
   */
  public abstract get fileRelativePath(): string;

  /**
   * Merges the existing file content with the new (template-generated) content.
   * @param existingContent - The content currently on disk
   * @param newContent - The content generated by the template
   * @returns The merged content string
   */
  public abstract merge(existingContent: string, newContent: string): string;
}
