// Copyright (c) Microsoft Corporation. All rights reserved. Licensed under the MIT license.
// See LICENSE in the project root for license information.

/**
 * Interface for merge helpers that handle merging file contents
 * when a template modifies an existing file.
 *
 * @public
 */
export interface IMergeHelper {
  /**
   * The relative file path this merge helper handles (e.g. "package.json").
   */
  readonly fileRelativePath: string;

  /**
   * Merges the existing file content with the new (template-generated) content.
   *
   * The returned string is the complete merged file content ready to be written
   * to disk — it is not a diff or patch. Implementations should be deterministic
   * and side-effect-free.
   *
   * @param existingContent - The content currently on disk
   * @param newContent - The content generated by the template
   * @returns The merged content string, ready to be written to disk as-is
   */
  merge(existingContent: string, newContent: string): string;
}
